---
title: "Stat 585 Lab 4 - Group 5"
author: "Katherine Goode, Gina Nichols, Xiyuan Sun, Ying Zheng"
date: "04/21/2019"
output: rmarkdown::github_document
always_allow_html: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Our GitHub repository for this lab can be found [here](https://github.com/xiyuansun/stat585Lab4).

```{r message = FALSE}
# Load libraries
library(tidyverse)
#Read in data
story_liquor <- read_csv("data/Iowa_Liquor_Sales-Story.csv")

```

# Iowa Liquor Sales Data

### Demonstration of Reading the Data from the API

### Data Cleaning

```{r dat clean}

newdat <- 
  story_liquor %>%
  
  # Rename cols
  rename_all(funs(
  str_replace_all(., "[\\(\\)_\\/ ]", "") %>%
  tolower())) %>%
  
  # Get rid of weird extremes
  filter(saledollars > 0,
  volumesoldliters > 0,
  volumesoldgallons > 0,
  volumesoldliters < 250) %>%
  
  # I think Catherine will take care of this in her code
  mutate(categoryname = tolower(categoryname)) %>%
  
  # assign new simple categories
  mutate(
    catsimp = case_when(
      grepl("amaretto", categoryname) ~ "amaretto",
      grepl("brand", categoryname) ~ "brandy",
      grepl("creme", categoryname) ~ "creme",
      grepl("cocktail|sec", categoryname) ~ "general_mixer",
      grepl("spirit", categoryname) ~ "general_spirit",
      grepl("gin", categoryname) ~ "gin",
      grepl("liqueur", categoryname) ~ "liqueur",
      grepl("schnap", categoryname) ~ "schnapps",
      grepl("rum", categoryname) ~ "rum",
      grepl("special", categoryname) ~ "specialty",
      grepl("tequ|mez", categoryname) ~ "tequila",
      grepl("vodka", categoryname) ~ "vodka",
      grepl("whisk|bourb|scotch|rye", categoryname) ~ "whisky"
      )
)
      
```


# Shiny App Visualizations
